### ISSUE TITLE
ValueError: sampler should be an instance of torch.utils.data.Sampler

### ISSUE THREAD

**Issue by saigequn** [ruotianluo/DiscCaptioning#10]
pytorch 1.0.0 
```
bash eval.sh att_d1 test
```

Traceback (most recent call last):
  File "eval.py", line 146, in <module>
    vars(opt))
  File "/content/DiscCaptioning/eval_utils.py", line 92, in eval_split
    data = loader.get_batch(split)
  File "/content/DiscCaptioning/dataloader.py", line 137, in get_batch
    ix, tmp_wrapped = self._prefetch_process[split].get()
  File "/content/DiscCaptioning/dataloader.py", line 256, in get
    self.reset()
  File "/content/DiscCaptioning/dataloader.py", line 235, in reset
    collate_fn=lambda x: x[0]))
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 805, in __init__
    batch_sampler = BatchSampler(sampler, batch_size, drop_last)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/sampler.py", line 146, in __init__
    .format(sampler))
ValueError: sampler should be an instance of torch.utils.data.Sampler, but got sampler=[......]
Terminating BlobFetcher

**Comment by ruotianluo** [comment]
This is because of you are using pytorch 0.4+.

Try to follow changes here https://github.com/ruotianluo/ImageCaptioning.pytorch/blob/master/dataloader.py#L207 .
